---
version: 1.0.3
slug: dnshome_updater
name: DNSHome DDNS Updater
description: >-
  Automatically update DNSHome DDNS records
url: https://github.com/leubeem/Hass-DNSHome-Addon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
startup: application
boot: auto
options:
  domain: ""
  username: ""
  password: ""
  update_interval: 10800  # 3 hours in seconds
schema:
  domain: str
  username: str
  password: str
  update_interval: int(3600,86400)  # Min 1 hour, max 24 hours
ports: {}
init: false
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11
  armhf: ghcr.io/home-assistant/armhf-base-python:3.11
  armv7: ghcr.io/home-assistant/armv7-base-python:3.11
  i386: ghcr.io/home-assistant/i386-base-python:3.11