---
version: 2.0.0
slug: dnshome_updater
name: DNSHome DDNS Updater
description: >-
  Automatically update DNSHome DDNS records
url: https://github.com/leubeem/Hass-DNSHome-Addon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
startup: application
boot: auto
options:
  domain: ""
  username: ""
  password: ""
  update_interval: 10800  # 3 hours in seconds
schema:
  domain: str
  username: str
  password: str
  update_interval: int(3600,86400)  # Min 1 hour, max 24 hours
ports: {}
init: false
image: leubeema/dnshome_updater:latest